name: CI

on: 
  push:
    branches:
      - 2.4.4-alpine

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        chmod +x ./deploy.sh
        ./deploy.sh ${GITHUB_REF##*/}
