name: Docker Image CI

on: 
  push:
    branches:
      - 2.4.4-alpine

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Login to DockerHub
      run: docker login -u="nvtienanh" -p="${{ secrets.DOCKER_PASSWORD }}"
    - name: Deploy Docker image
      run: sh ./deploy.sh ${GITHUB_REF##*/}
      shell: bash
